apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: ls-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: ls-operator
  template:
    metadata:
      labels:
        application: ls-operator
    spec:
      serviceAccountName: default
      containers:
        - name: operator
          image: ls-operator
          imagePullPolicy: Never

