#  _  __     _                          _            
# | |/ /   _| |__   ___ _ __ _ __   ___| |_ ___  ___ 
# | ' / | | | '_ \ / _ \ '__| '_ \ / _ \ __/ _ \/ __|
# | . \ |_| | |_) |  __/ |  | | | |  __/ ||  __/\__ \
# |_|\_\__,_|_.__/ \___|_|  |_| |_|\___|\__\___||___/


# use the kubernetes executor for lambda functions
# note: this separate configuration should be removed as we have `CONTAINER_RUNTIME` now
lambda:
  executor: kubernetes

# use the Kubernetes runtime for supported containers
extraEnvVars:
  - name: CONTAINER_RUNTIME
    value: kubernetes

# -------------------------------------------------------
#
#       ___  _   _               
#  / _ \| |_| |__   ___ _ __ 
# | | | | __| '_ \ / _ \ '__|
# | |_| | |_| | | |  __/ |   
#  \___/ \__|_| |_|\___|_|   

# use the pro image
image:
  repository: localstack/localstack-pro

# enable debug logs
debug: true

# increase the probe timeouts as LocalStack takes a little while to start
livenessProbe:
  initialDelaySeconds: 10
  failureThreshold: 5
readinessProbe:
  initialDelaySeconds: 10
  failureThreshold: 5

# ensure the pod has enough capacity to run
resources:
  requests:
    cpu: 1
    memory: 512Mi
  requests:
    cpu: 2
    memory: 1024Mi

service:
  # defaults to NodePort which we don't need
  type: ClusterIP

  # expose the LocalStack DNS server in the service
  dnsService: true

# Don't use the cluster DNS server since we will be setting it to LocalStack,
# and this will cause loops
dnsPolicy: Default
